"""
StockAggressivePredictor — Offline Inference for Aggressive C Strategy.

Loads multi-horizon artifacts generated by local_training_aggressive.py:
- Huber + Tweedie ensemble (calibrated via IsotonicRegression) for mean demand
- P85 Quantile XGBoost for safety stock (replaces simplistic buffers)
- Per-horizon Target Encoders
"""
import pandas as pd
import numpy as np
import xgboost as xgb
import os
import joblib
from sqlalchemy import select
from sqlalchemy.orm import Session
from typing import List, Dict, Any, Optional
from datetime import datetime

from domains.intelligence.models import MLFeatureStore

MODEL_ARTIFACTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts_aggressive")
HORIZONS = [7, 14, 21, 28]

class SklearnCompatibleXGBRegressor(xgb.XGBRegressor):
    def __sklearn_tags__(self):
        tags = super().__sklearn_tags__()
        tags.estimator_type = "regressor"
        return tags

class StockAggressivePredictor:
    def __init__(self, db_session: Session):
        self.db = db_session
        self.models_huber: Dict[int, Any] = {}
        self.models_tweedie: Dict[int, Any] = {}
        self.models_quantile: Dict[int, Any] = {}
        self.calibrators: Dict[int, Any] = {}
        self.encoders: Dict[int, Any] = {}
        
        self.features_order = [
            'store_nbr', 'family', 'city', 'state', 'cluster', 'store_type',
            'rolling_7d_sales', 'rolling_14d_sales', 'rolling_30d_sales', 'rolling_7d_std',
            'is_weekend', 'days_since_payday', 'onpromotion',
            'lag_1', 'lag_2', 'lag_3', 'lag_7', 'lag_14', 'lag_30',
            'day_of_week', 'is_month_end', 'is_holiday_or_event', 'days_to_next_holiday',
            'oil_price'
        ]
        self.model_version = "stock_aggressive_loaded"
        self.is_loaded = False

    def _feature_select(self):
        return select(
            MLFeatureStore.store_nbr,
            MLFeatureStore.family,
            MLFeatureStore.date,
            MLFeatureStore.city,
            MLFeatureStore.state,
            MLFeatureStore.cluster,
            MLFeatureStore.store_type,
            MLFeatureStore.rolling_7d_sales,
            MLFeatureStore.rolling_14d_sales,
            MLFeatureStore.rolling_30d_sales,
            MLFeatureStore.rolling_7d_std,
            MLFeatureStore.is_weekend,
            MLFeatureStore.days_since_payday,
            MLFeatureStore.onpromotion,
            MLFeatureStore.lag_1,
            MLFeatureStore.lag_2,
            MLFeatureStore.lag_3,
            MLFeatureStore.lag_7,
            MLFeatureStore.lag_14,
            MLFeatureStore.lag_30,
            MLFeatureStore.day_of_week,
            MLFeatureStore.is_month_end,
            MLFeatureStore.is_holiday_or_event,
            MLFeatureStore.days_to_next_holiday,
            MLFeatureStore.oil_price
        )

    def _rows_to_dataframe(self, results) -> pd.DataFrame:
        if not results:
            return pd.DataFrame()
        cols = self.features_order.copy()
        cols.insert(2, 'date')
        df = pd.DataFrame(results, columns=cols)
        df['date'] = pd.to_datetime(df['date'])
        for col in ['is_weekend', 'is_month_end', 'is_holiday_or_event']:
            df[col] = df[col].astype(int)
        df['city'] = df['city'].fillna('UNKNOWN')
        df['state'] = df['state'].fillna('UNKNOWN')
        df['store_type'] = df['store_type'].fillna('UNKNOWN')

        numeric_cols = [
            'store_nbr', 'cluster', 'rolling_7d_sales', 'rolling_14d_sales', 'rolling_30d_sales',
            'rolling_7d_std', 'days_since_payday', 'onpromotion',
            'lag_1', 'lag_2', 'lag_3', 'lag_7', 'lag_14', 'lag_30',
            'day_of_week', 'oil_price', 'days_to_next_holiday'
        ]
        for col in numeric_cols:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

        df.sort_values(['date', 'store_nbr', 'family'], inplace=True)
        df.reset_index(drop=True, inplace=True)
        return df

    def fetch_latest_features(self) -> pd.DataFrame:
        latest_date = self.db.execute(
            select(MLFeatureStore.date).order_by(MLFeatureStore.date.desc()).limit(1)
        ).scalar_one_or_none()

        if latest_date is None:
            return pd.DataFrame()

        query = (
            self._feature_select()
            .where(MLFeatureStore.date == latest_date)
            .order_by(MLFeatureStore.store_nbr, MLFeatureStore.family)
        )
        results = self.db.execute(query).fetchall()
        return self._rows_to_dataframe(results)

    def load_artifacts(self) -> bool:
        if self.is_loaded:
            return True

        if not os.path.exists(MODEL_ARTIFACTS_DIR):
            print(f"[AggressivePredictor] Directory {MODEL_ARTIFACTS_DIR} not found.")
            return False

        all_exist = all(
            os.path.exists(os.path.join(MODEL_ARTIFACTS_DIR, f"{prefix}_aggressive_{h}d.joblib"))
            for h in HORIZONS
            for prefix in ["encoder", "huber", "tweedie", "quantile_p85", "isotonic"]
        )

        if not all_exist:
            print("[AggressivePredictor] Missing some aggressive artifacts! Ensure local_training_aggressive.py is run.")
            return False

        print("\n[AggressivePredictor] Loading offline trained aggressive models (Huber+Tweedie+Quantile+Isotonic)...")
        for h in HORIZONS:
            self.encoders[h] = joblib.load(os.path.join(MODEL_ARTIFACTS_DIR, f"encoder_aggressive_{h}d.joblib"))
            self.models_huber[h] = joblib.load(os.path.join(MODEL_ARTIFACTS_DIR, f"huber_aggressive_{h}d.joblib"))
            self.models_tweedie[h] = joblib.load(os.path.join(MODEL_ARTIFACTS_DIR, f"tweedie_aggressive_{h}d.joblib"))
            self.models_quantile[h] = joblib.load(os.path.join(MODEL_ARTIFACTS_DIR, f"quantile_p85_aggressive_{h}d.joblib"))
            self.calibrators[h] = joblib.load(os.path.join(MODEL_ARTIFACTS_DIR, f"isotonic_aggressive_{h}d.joblib"))
        
        self.is_loaded = True
        return True

    @staticmethod
    def _clip_predictions(predictions) -> np.ndarray:
        return np.clip(np.asarray(predictions, dtype=float), 0, None)

    def predict_latest(self) -> List[Dict[str, Any]]:
        success = self.load_artifacts()
        
        if not success:
            print("[AggressivePredictor] Inference skipped, models missing.")
            return []

        df_latest = self.fetch_latest_features()
        if df_latest.empty:
            return []

        # Convert target engineered formats just like in local_training
        X_infer = df_latest[self.features_order].copy()
        
        for col in self.features_order:
            if col in ['city', 'state', 'store_type']:
                X_infer[col] = X_infer[col].fillna("UNKNOWN")

        predictions = []
        for horizon in HORIZONS:
            # Important: the TargetEncoder transform matches fit variables.
            X_infer_encoded = self.encoders[horizon].transform(X_infer)
            
            preds_h = self._clip_predictions(self.models_huber[horizon].predict(X_infer_encoded))
            preds_t = self._clip_predictions(self.models_tweedie[horizon].predict(X_infer_encoded))
            raw_ensemble = (preds_h + preds_t) / 2.0
            
            calibrated_mean = self._clip_predictions(self.calibrators[horizon].predict(raw_ensemble))

            raw_p85 = self._clip_predictions(self.models_quantile[horizon].predict(X_infer_encoded))
            
            # Since additive coverage offset relies on y_cal residuals during training,
            # using raw_p85 uncalibrated is directly reliable for pure safety limits baseline.
            p85_demand = raw_p85

            for i, idx in enumerate(df_latest.index):
                row = df_latest.loc[idx]
                mean_val = float(calibrated_mean[i])
                p85_val = float(p85_demand[i])
                
                mean_val = max(mean_val, 0.0)
                p85_val = max(mean_val, p85_val)
                
                total_mean_demand = mean_val * horizon
                total_p85_demand = p85_val * horizon
                
                recommended_stock = int(np.ceil(total_p85_demand))
                safety_buffer = max(float(p85_val - mean_val), 0.0)
                
                story = (
                    f"Prediksi mean demand ({horizon}d): {mean_val:.1f}/hari. "
                    f"P85 Quantile prediksi batas pesimis: {p85_val:.1f}/hari. "
                    f"Total expected safety threshold demand: {total_p85_demand:.0f} "
                    f"-> Rekomendasi stok ditetapkan: {recommended_stock} qty."
                )

                predictions.append({
                    "store_nbr": int(row['store_nbr']),
                    "family": str(row['family']),
                    "predicted_for_date": (row['date'] + pd.Timedelta(days=horizon)).date(),
                    "prediction_type": "stock_demand",
                    "predicted_value": mean_val,
                    "recommended_stock": recommended_stock,
                    "safety_stock_buffer": safety_buffer,
                    "safety_stock_source": "p85_quantile_regression",
                    "reasoning_text": story,
                    "model_version": self.model_version,
                    "horizon_days": horizon,
                    "prediction_level": "family",
                })

        print(f"[AggressivePredictor] {len(predictions)} prediksi multi-horizon siap via Aggressive Models.")
        return predictions
